import yaml
import importlib.resources
from PyQt6.QtWidgets import QFrame, QGroupBox, QHBoxLayout, QFormLayout, QLabel, QDoubleSpinBox, \
    QSpinBox, QComboBox, QCheckBox


class SignalConfigurationFrame(QFrame):

    def __init__(self):
        super(SignalConfigurationFrame, self).__init__()

        # Main Layout
        self.main_layout = QHBoxLayout()
        self.setLayout(self.main_layout)

        self.strings = {}
        with importlib.resources.path("resources.strings", 'strings.yaml') as path:
            with open(path) as f:
                self.strings = yaml.safe_load(f)

        # Sensor Configuration GB
        self.sensor_config_gb = QGroupBox('Profile Configuration')
        self.main_layout.addWidget(self.sensor_config_gb)
        # GP Layout
        self.form_layout = QFormLayout()
        self.sensor_config_gb.setLayout(self.form_layout)
        # Profile & spinbox
        self.profile = QLabel('Profile ID')
        self.profile.setToolTip(self.strings['SignalConfigurationFrame']['profile'][0])
        self.profile_sb = QSpinBox()
        self.form_layout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.profile)
        self.form_layout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.profile_sb)
        # Start Freq & spinbox
        self.start_freq = QLabel('Start Freq')
        self.start_freq.setToolTip(self.strings['SignalConfigurationFrame']['start_freq'][0])
        self.start_freq_sb = QDoubleSpinBox()
        self.start_freq_sb.setDecimals(6)
        self.start_freq_sb.setValue(77.000000)
        self.start_freq_sb.setMaximum(81.000000)
        self.start_freq_sb.setMinimum(76.000000)
        self.form_layout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.start_freq)
        self.form_layout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.start_freq_sb)
        # Freq slope & spinbox
        self.freq_slope = QLabel('Freq slope')
        self.freq_slope.setToolTip(self.strings['SignalConfigurationFrame']['freq_slope'][0])
        self.freq_slope_sb = QDoubleSpinBox()
        self.freq_slope_sb.setDecimals(3)
        self.freq_slope_sb.setValue(29.982)
        self.form_layout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.freq_slope)
        self.form_layout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.freq_slope_sb)
        # Idle Time & spinbox
        self.idle_time = QLabel('Idle Time')
        self.idle_time.setToolTip(self.strings['SignalConfigurationFrame']['idle_time'][0])
        self.idle_time_sb = QDoubleSpinBox()
        self.idle_time_sb.setMaximum(5242.87)
        self.idle_time_sb.setValue(100.00)
        self.form_layout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.idle_time)
        self.form_layout.setWidget(3, QFormLayout.ItemRole.FieldRole, self.idle_time_sb)
        # ADC Start Time & spinbox
        self.adc_st = QLabel('ADC Start Time')
        self.adc_st.setToolTip(self.strings['SignalConfigurationFrame']['adc_st'][0])
        self.adc_st_sb = QDoubleSpinBox()
        self.adc_st_sb.setValue(6.00)
        self.adc_st_sb.setMaximum(40.95)
        self.form_layout.setWidget(4, QFormLayout.ItemRole.LabelRole, self.adc_st)
        self.form_layout.setWidget(4, QFormLayout.ItemRole.FieldRole, self.adc_st_sb)
        # Ramp End Time & spinbox
        self.ramp_et = QLabel('Ramp End Time')
        self.ramp_et.setToolTip(self.strings['SignalConfigurationFrame']['ramp_et'][0])
        self.ramp_et_sb = QDoubleSpinBox()
        self.ramp_et_sb.setValue(60.00)
        self.ramp_et_sb.setMaximum(5000.00)
        self.form_layout.setWidget(5, QFormLayout.ItemRole.LabelRole, self.ramp_et)
        self.form_layout.setWidget(5, QFormLayout.ItemRole.FieldRole, self.ramp_et_sb)
        # TX Out Power Backoff Code & spinbox
        self.tx_Out_Power_Backoff_Code = QLabel('TX Out Power Backoff Code')
        self.tx_Out_Power_Backoff_Code.setToolTip(self.strings['SignalConfigurationFrame']
                                                  ['tx_Out_Power_Backoff_Code'][0])
        self.tx_Out_Power_Backoff_Code_sb = QDoubleSpinBox()
        self.tx_Out_Power_Backoff_Code_sb.setMaximum(20)
        self.form_layout.setWidget(6, QFormLayout.ItemRole.LabelRole, self.tx_Out_Power_Backoff_Code)
        self.form_layout.setWidget(6, QFormLayout.ItemRole.FieldRole, self.tx_Out_Power_Backoff_Code_sb)
        # TX Phase Shifter & spinbox
        self.tx_Phase_Shifter = QLabel('TX Phase Shifter')
        self.tx_Phase_Shifter.setToolTip(self.strings['SignalConfigurationFrame']['tx_Phase_Shifter'][0])
        self.tx_Phase_Shifter_sb = QDoubleSpinBox()
        self.form_layout.setWidget(7, QFormLayout.ItemRole.LabelRole, self.tx_Phase_Shifter)
        self.form_layout.setWidget(7, QFormLayout.ItemRole.FieldRole, self.tx_Phase_Shifter_sb)
        # TX Start Time & spinbox
        self.tx_Start_Time = QLabel('TX Start Time')
        self.tx_Start_Time.setToolTip(self.strings['SignalConfigurationFrame']['tx_Start_Time'][0])
        self.tx_Start_Time_sb = QDoubleSpinBox()
        self.tx_Start_Time_sb.setMaximum(40.95)
        self.tx_Start_Time_sb.setMinimum(-40.96)
        self.form_layout.setWidget(8, QFormLayout.ItemRole.LabelRole, self.tx_Start_Time)
        self.form_layout.setWidget(8, QFormLayout.ItemRole.FieldRole, self.tx_Start_Time_sb)
        # Num ADC Samples & spinbox
        self.num_Adc_Samples_profile = QLabel('Num ADC Samples')
        self.num_Adc_Samples_profile.setToolTip(self.strings['SignalConfigurationFrame']['num_Adc_Samples_profile'][0])
        self.num_Adc_Samples_profile_sb = QSpinBox()
        self.num_Adc_Samples_profile_sb.setMaximum(4096)
        self.num_Adc_Samples_profile_sb.setValue(256)
        self.form_layout.setWidget(9, QFormLayout.ItemRole.LabelRole, self.num_Adc_Samples_profile)
        self.form_layout.setWidget(9, QFormLayout.ItemRole.FieldRole, self.num_Adc_Samples_profile_sb)
        # Dig Out Sample Rate & spinbox
        self.dig_Out_Sample_Rate = QLabel('Sample Rate')
        self.dig_Out_Sample_Rate.setToolTip(self.strings['SignalConfigurationFrame']['dig_Out_Sample_Rate'][0])
        self.dig_Out_Sample_Rate_sb = QSpinBox()
        self.dig_Out_Sample_Rate_sb.setMaximum(37500)
        self.dig_Out_Sample_Rate_sb.setMinimum(2000)
        self.dig_Out_Sample_Rate_sb.setValue(10000)
        self.form_layout.setWidget(10, QFormLayout.ItemRole.LabelRole, self.dig_Out_Sample_Rate)
        self.form_layout.setWidget(10, QFormLayout.ItemRole.FieldRole, self.dig_Out_Sample_Rate_sb)
        # HPF 1 Corner Freq & spinbox
        self.hpf_Corner_Freq1 = QLabel('HPF 1 Corner Freq')
        self.hpf_Corner_Freq1.setToolTip(self.strings['SignalConfigurationFrame']['hpf_Corner_Freq1'][0])
        self.hpf_Corner_Freq1_cb = QComboBox()
        self.hpf_Corner_Freq1_cb.addItem('175K', 0)
        self.hpf_Corner_Freq1_cb.addItem('235K', 1)
        self.hpf_Corner_Freq1_cb.addItem('350K', 2)
        self.hpf_Corner_Freq1_cb.addItem('700K', 3)
        self.form_layout.setWidget(11, QFormLayout.ItemRole.LabelRole, self.hpf_Corner_Freq1)
        self.form_layout.setWidget(11, QFormLayout.ItemRole.FieldRole, self.hpf_Corner_Freq1_cb)
        # HPF 2 Corner Freq & spinbox
        self.hpf_Corner_Freq2 = QLabel('HPF 2 Corner Freq')
        self.hpf_Corner_Freq2.setToolTip(self.strings['SignalConfigurationFrame']['hpf_Corner_Freq2'][0])
        self.hpf_Corner_Freq2_cb = QComboBox()
        self.hpf_Corner_Freq2_cb.addItem('350K', 0)
        self.hpf_Corner_Freq2_cb.addItem('700K', 1)
        self.hpf_Corner_Freq2_cb.addItem('1.4M', 2)
        self.hpf_Corner_Freq2_cb.addItem('2.8M', 3)
        self.form_layout.setWidget(12, QFormLayout.ItemRole.LabelRole, self.hpf_Corner_Freq2)
        self.form_layout.setWidget(12, QFormLayout.ItemRole.FieldRole, self.hpf_Corner_Freq2_cb)
        # RX Gain & spinbox
        self.rx_Gain = QLabel('RX Gain')
        self.rx_Gain.setToolTip(self.strings['SignalConfigurationFrame']['rx_Gain'][0])
        self.rx_Gain_sb = QSpinBox()
        self.rx_Gain_sb.setMaximum(52)
        self.rx_Gain_sb.setMinimum(24)
        self.rx_Gain_sb.setValue(24)
        self.form_layout.setWidget(13, QFormLayout.ItemRole.LabelRole, self.rx_Gain)
        self.form_layout.setWidget(13, QFormLayout.ItemRole.FieldRole, self.rx_Gain_sb)

        # Chirp Configuration GB
        self.chirp_config_gb = QGroupBox('Chirp Configuration')
        self.main_layout.addWidget(self.chirp_config_gb)
        # GP Layout
        self.form_layout_chirp = QFormLayout()
        self.chirp_config_gb.setLayout(self.form_layout_chirp)
        # Profile id & spinbox
        self.profile_Id = QLabel('Profile id')
        self.profile_Id.setToolTip(self.strings['SignalConfigurationFrame']['profile_Id'][0])
        self.profile_Id_sb = QSpinBox()
        self.form_layout_chirp.setWidget(0, QFormLayout.ItemRole.LabelRole, self.profile_Id)
        self.form_layout_chirp.setWidget(0, QFormLayout.ItemRole.FieldRole, self.profile_Id_sb)
        # Chirp Start id & spinbox
        self.chirp_Start_Idx = QLabel('Chirp Start id')
        self.chirp_Start_Idx.setToolTip(self.strings['SignalConfigurationFrame']['chirp_Start_Idx'][0])
        self.chirp_Start_Idx_sb = QSpinBox()
        self.chirp_Start_Idx_sb.setMaximum(511)
        self.form_layout_chirp.setWidget(1, QFormLayout.ItemRole.LabelRole, self.chirp_Start_Idx)
        self.form_layout_chirp.setWidget(1, QFormLayout.ItemRole.FieldRole, self.chirp_Start_Idx_sb)
        # Chirp End id & spinbox
        self.chirp_End_Idx = QLabel('Chirp End id')
        self.chirp_End_Idx.setToolTip(self.strings['SignalConfigurationFrame']['chirp_End_Idx'][0])
        self.chirp_End_Idx_sb = QSpinBox()
        self.chirp_End_Idx_sb.setMaximum(511)
        self.form_layout_chirp.setWidget(2, QFormLayout.ItemRole.LabelRole, self.chirp_End_Idx)
        self.form_layout_chirp.setWidget(2, QFormLayout.ItemRole.FieldRole, self.chirp_End_Idx_sb)
        # Start Freq Var & spinbox
        self.start_Freq_Var = QLabel('Start Freq Var')
        self.start_Freq_Var.setToolTip(self.strings['SignalConfigurationFrame']['start_Freq_Var'][0])
        self.start_Freq_Var_sb = QDoubleSpinBox()
        # self.start_Freq_Var_sb.setMaximum()
        self.start_Freq_Var_sb.setDecimals(6)
        self.form_layout_chirp.setWidget(3, QFormLayout.ItemRole.LabelRole, self.start_Freq_Var)
        self.form_layout_chirp.setWidget(3, QFormLayout.ItemRole.FieldRole, self.start_Freq_Var_sb)
        # Freq Slope Var & spinbox
        self.freq_Slope_Var = QLabel('Freq Slope Var')
        self.freq_Slope_Var.setToolTip(self.strings['SignalConfigurationFrame']['freq_Slope_Var'][0])
        self.freq_Slope_Var_sb = QDoubleSpinBox()
        # self.freq_Slope_Var_sb.setMaximum()
        self.freq_Slope_Var_sb.setDecimals(3)
        self.form_layout_chirp.setWidget(4, QFormLayout.ItemRole.LabelRole, self.freq_Slope_Var)
        self.form_layout_chirp.setWidget(4, QFormLayout.ItemRole.FieldRole, self.freq_Slope_Var_sb)
        # Idle Time Var & spinbox
        self.idle_Time_Var = QLabel('Idle Time Var')
        self.idle_Time_Var.setToolTip(self.strings['SignalConfigurationFrame']['idle_Time_Var'][0])
        self.idle_Time_Var_sb = QDoubleSpinBox()
        self.idle_Time_Var_sb.setMaximum(40.96)
        self.form_layout_chirp.setWidget(5, QFormLayout.ItemRole.LabelRole, self.idle_Time_Var)
        self.form_layout_chirp.setWidget(5, QFormLayout.ItemRole.FieldRole, self.idle_Time_Var_sb)
        # ADC Start Time Var & spinbox
        self.adc_Start_Time_Var = QLabel('ADC Start Time Var')
        self.adc_Start_Time_Var.setToolTip(self.strings['SignalConfigurationFrame']['adc_Start_Time_Var'][0])
        self.adc_Start_Time_Var_sb = QDoubleSpinBox()
        self.adc_Start_Time_Var_sb.setMaximum(40.96)
        self.form_layout_chirp.setWidget(6, QFormLayout.ItemRole.LabelRole, self.adc_Start_Time_Var)
        self.form_layout_chirp.setWidget(6, QFormLayout.ItemRole.FieldRole, self.adc_Start_Time_Var_sb)
        # TX Enable & spinbox
        self.tx_Enable = QLabel('TX Enable')
        self.tx_Enable.setToolTip(self.strings['SignalConfigurationFrame']['tx_Enable'][0])
        self.tx_Enable_h_layout = QHBoxLayout()
        # Tx0
        self.tx0_en = QLabel('TX0')
        self.tx0_en_cb = QCheckBox()
        self.tx0_en_cb.setChecked(True)
        self.tx0_en_form = QFormLayout()
        self.tx0_en_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.tx0_en)
        self.tx0_en_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.tx0_en_cb)
        self.tx_Enable_h_layout.addLayout(self.tx0_en_form)
        # Tx1
        self.tx1_en = QLabel('TX1')
        self.tx1_en_cb = QCheckBox()
        self.tx1_en_cb.setChecked(True)
        self.tx1_en_form = QFormLayout()
        self.tx1_en_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.tx1_en)
        self.tx1_en_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.tx1_en_cb)
        self.tx_Enable_h_layout.addLayout(self.tx1_en_form)
        # Tx2
        self.tx2_en = QLabel('TX2')
        self.tx2_en_cb = QCheckBox()
        self.tx2_en_form = QFormLayout()
        self.tx2_en_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.tx2_en)
        self.tx2_en_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.tx2_en_cb)
        self.tx_Enable_h_layout.addLayout(self.tx2_en_form)
        self.form_layout_chirp.setWidget(7, QFormLayout.ItemRole.LabelRole, self.tx_Enable)
        self.form_layout_chirp.setLayout(7, QFormLayout.ItemRole.FieldRole, self.tx_Enable_h_layout)

        # Frame Configuration GB
        self.frame_config_gb = QGroupBox('Frame Configuration')
        self.main_layout.addWidget(self.frame_config_gb)
        # GP Layout
        self.form_layout_frame = QFormLayout()
        self.frame_config_gb.setLayout(self.form_layout_frame)
        # Chirp Start id & spinbox
        self.chirp_Start_Id = QLabel('Chirp Start id')
        self.chirp_Start_Id.setToolTip(self.strings['SignalConfigurationFrame']['chirp_Start_Id'][0])
        self.chirp_Start_Id_sb = QSpinBox()
        self.chirp_Start_Id_sb.setMaximum(511)
        self.form_layout_frame.setWidget(0, QFormLayout.ItemRole.LabelRole, self.chirp_Start_Id)
        self.form_layout_frame.setWidget(0, QFormLayout.ItemRole.FieldRole, self.chirp_Start_Id_sb)
        # Chirp End id & spinbox
        self.chirp_End_Id = QLabel('Chirp End id')
        self.chirp_End_Id.setToolTip(self.strings['SignalConfigurationFrame']['chirp_End_Id'][0])
        self.chirp_End_Id_sb = QSpinBox()
        self.chirp_End_Id_sb.setMaximum(511)
        self.form_layout_frame.setWidget(1, QFormLayout.ItemRole.LabelRole, self.chirp_End_Id)
        self.form_layout_frame.setWidget(1, QFormLayout.ItemRole.FieldRole, self.chirp_End_Id_sb)
        # Frame Count & spinbox
        self.frame_Count = QLabel('Frame Count')
        self.frame_Count.setToolTip(self.strings['SignalConfigurationFrame']['frame_Count'][0])
        self.frame_Count_sb = QSpinBox()
        self.frame_Count_sb.setMaximum(65535)
        self.form_layout_frame.setWidget(2, QFormLayout.ItemRole.LabelRole, self.frame_Count)
        self.form_layout_frame.setWidget(2, QFormLayout.ItemRole.FieldRole, self.frame_Count_sb)
        # Loop Count & spinbox
        self.loop_Count = QLabel('Loop Count')
        self.loop_Count.setToolTip(self.strings['SignalConfigurationFrame']['loop_Count'][0])
        self.loop_Count_sb = QSpinBox()
        self.loop_Count_sb.setMaximum(255)
        self.loop_Count_sb.setMinimum(1)
        self.form_layout_frame.setWidget(3, QFormLayout.ItemRole.LabelRole, self.loop_Count)
        self.form_layout_frame.setWidget(3, QFormLayout.ItemRole.FieldRole, self.loop_Count_sb)
        # Periodicity & spinbox
        self.periodicity = QLabel('Periodicity')
        self.periodicity.setToolTip(self.strings['SignalConfigurationFrame']['periodicity'][0])
        self.periodicity_sb = QDoubleSpinBox()
        self.periodicity_sb.setDecimals(7)
        self.periodicity_sb.setValue(40.0000000)
        self.periodicity_sb.setMaximum(1342.0000000)
        self.periodicity_sb.setMinimum(0.0000003)
        self.form_layout_frame.setWidget(4, QFormLayout.ItemRole.LabelRole, self.periodicity)
        self.form_layout_frame.setWidget(4, QFormLayout.ItemRole.FieldRole, self.periodicity_sb)
        # Trigger Delay & spinbox
        self.trigger_Delay = QLabel('Trigger Delay')
        self.trigger_Delay.setToolTip(self.strings['SignalConfigurationFrame']['trigger_Delay'][0])
        self.trigger_Delay_sb = QDoubleSpinBox()
        self.trigger_Delay_sb.setDecimals(3)
        self.trigger_Delay_sb.setMaximum(10.000)
        self.form_layout_frame.setWidget(5, QFormLayout.ItemRole.LabelRole, self.trigger_Delay)
        self.form_layout_frame.setWidget(5, QFormLayout.ItemRole.FieldRole, self.trigger_Delay_sb)
        # Num ADC Samples & spinbox
        self.num_Adc_Samples_frame = QLabel('Num ADC Samples')
        self.num_Adc_Samples_frame.setToolTip(self.strings['SignalConfigurationFrame']['num_Adc_Samples_frame'][0])
        self.num_Adc_Samples_frame_sb = QSpinBox()
        self.form_layout_frame.setWidget(6, QFormLayout.ItemRole.LabelRole, self.num_Adc_Samples_frame)
        self.form_layout_frame.setWidget(6, QFormLayout.ItemRole.FieldRole, self.num_Adc_Samples_frame_sb)
        # Trigger Select & spinbox
        self.trigger_Select = QLabel('Trigger Select')
        self.trigger_Select.setToolTip(self.strings['SignalConfigurationFrame']['trigger_Select'][0])
        self.trigger_Select_cb = QComboBox()
        self.trigger_Select_cb.addItem('Software Trigger', 0)
        self.trigger_Select_cb.addItem('Hardware Trigger', 1)
        self.form_layout_frame.setWidget(7, QFormLayout.ItemRole.LabelRole, self.trigger_Select)
        self.form_layout_frame.setWidget(7, QFormLayout.ItemRole.FieldRole, self.trigger_Select_cb)
