from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QFrame, QPushButton, QVBoxLayout, QHBoxLayout, QLabel, QGroupBox, \
    QSpinBox, QFormLayout, QCheckBox, QGridLayout, QComboBox, QSizePolicy


class StartFrame(QFrame):

    def __init__(self, strings: dict):
        super(StartFrame, self).__init__()

        self.strings = strings

        # Main layout
        self.main_layout = QVBoxLayout()
        self.setLayout(self.main_layout)

        # Channel configuration parameters gb
        self.channel_config_gb = QGroupBox(self.strings['StartFrame']['GroupBoxes'][0])
        self.grid_layout_ch_config = QGridLayout()
        self.main_layout.addWidget(self.channel_config_gb)
        self.channel_config_gb.setLayout(self.grid_layout_ch_config)
        # channelTx
        self.channel_Tx = QLabel(self.strings['StartFrame']['channel_Tx'][0])
        self.channel_Tx.setToolTip(self.strings['StartFrame']['channel_Tx'][1])
        self.grid_layout_ch_config.addWidget(self.channel_Tx, 0, 0)
        # Tx0
        self.form_layout_Tx0 = QFormLayout()
        self.Tx0 = QLabel(self.strings['StartFrame']['channel_Tx'][2])
        self.Tx0_cb = QCheckBox()
        self.Tx0_cb.setChecked(True)
        self.form_layout_Tx0.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Tx0)
        self.form_layout_Tx0.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Tx0_cb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Tx0, 0, 1)
        # Tx1
        self.Tx1 = QLabel(self.strings['StartFrame']['channel_Tx'][3])
        self.form_layout_Tx1 = QFormLayout()
        self.Tx1_cb = QCheckBox()
        self.Tx1_cb.setChecked(True)
        self.form_layout_Tx1.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Tx1)
        self.form_layout_Tx1.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Tx1_cb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Tx1, 0, 2)
        # Tx2
        self.Tx2 = QLabel(self.strings['StartFrame']['channel_Tx'][4])
        self.form_layout_Tx2 = QFormLayout()
        self.Tx2_cb = QCheckBox()
        self.Tx2_cb.setEnabled(False)
        self.form_layout_Tx2.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Tx2)
        self.form_layout_Tx2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Tx2_cb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Tx2, 0, 3)
        # channelRx
        self.channel_Rx = QLabel(self.strings['StartFrame']['channel_Rx'][0])
        self.channel_Rx.setToolTip(self.strings['StartFrame']['channel_Rx'][1])
        self.grid_layout_ch_config.addWidget(self.channel_Rx, 1, 0)
        # Rx0
        self.form_layout_Rx0 = QFormLayout()
        self.Rx0 = QLabel(self.strings['StartFrame']['channel_Rx'][2])
        self.Rx0_cb = QCheckBox()
        self.Rx0_cb.setChecked(True)
        self.form_layout_Rx0.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx0)
        self.form_layout_Rx0.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx0_cb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx0, 1, 1)
        # Rx1
        self.Rx1 = QLabel(self.strings['StartFrame']['channel_Rx'][3])
        self.form_layout_Rx1 = QFormLayout()
        self.Rx1_cb = QCheckBox()
        self.Rx1_cb.setChecked(True)
        self.form_layout_Rx1.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx1)
        self.form_layout_Rx1.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx1_cb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx1, 1, 2)
        # Rx2
        self.Rx2 = QLabel(self.strings['StartFrame']['channel_Rx'][4])
        self.form_layout_Rx2 = QFormLayout()
        self.Rx2_cb = QCheckBox()
        self.Rx2_cb.setChecked(True)
        self.form_layout_Rx2.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx2)
        self.form_layout_Rx2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx2_cb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx2, 1, 3)
        # Rx3
        self.Rx3 = QLabel(self.strings['StartFrame']['channel_Rx'][5])
        self.form_layout_Rx3 = QFormLayout()
        self.Rx3_cb = QCheckBox()
        self.Rx3_cb.setChecked(True)
        self.form_layout_Rx3.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx3)
        self.form_layout_Rx3.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx3_cb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx3, 1, 4)
        # Degree resolution
        self.degree_resolution_label = QLabel(self.strings['StartFrame']['degree_resolution'][0])
        self.grid_layout_ch_config.addWidget(self.degree_resolution_label, 2, 0)
        # Degree val
        self.degree_val_label = QLabel(self.strings['StartFrame']['degree_resolution'][1])
        self.grid_layout_ch_config.addWidget(self.degree_val_label, 2, 1)
        # Cascading Mode
        self.cascading_Mode = QLabel(self.strings['StartFrame']['cascading_Mode'][0])
        self.cascading_Mode.setToolTip(self.strings['StartFrame']['cascading_Mode'][1])
        self.grid_layout_ch_config.addWidget(self.cascading_Mode, 3, 0)
        self.cascading_Mode_cb = QComboBox()
        self.cascading_Mode_cb.addItem(self.strings['StartFrame']['cascading_Mode'][2], 0)
        self.cascading_Mode_cb.addItem(self.strings['StartFrame']['cascading_Mode'][3], 1)
        self.cascading_Mode_cb.addItem(self.strings['StartFrame']['cascading_Mode'][4], 2)
        self.cascading_Mode_cb.model().item(1).setEnabled(False)
        self.cascading_Mode_cb.model().item(2).setEnabled(False)
        self.grid_layout_ch_config.addWidget(self.cascading_Mode_cb, 3, 1)

        # ADC out configuration parameters gb
        self.ADC_out_config_gb = QGroupBox(self.strings['StartFrame']['GroupBoxes'][1])
        self.form_layout_adc_conf = QFormLayout()
        self.main_layout.addWidget(self.ADC_out_config_gb)
        # ADC Bits
        self.adc_Bits = QLabel(self.strings['StartFrame']['adc_Bits'][0])
        self.adc_Bits.setToolTip(self.strings['StartFrame']['adc_Bits'][1])
        self.adc_Bits_cb = QComboBox()
        self.adc_Bits_cb.addItem(self.strings['StartFrame']['adc_Bits'][2], 0)
        self.adc_Bits_cb.addItem(self.strings['StartFrame']['adc_Bits'][3], 1)
        self.adc_Bits_cb.addItem(self.strings['StartFrame']['adc_Bits'][4], 2)
        self.adc_Bits_cb.setCurrentIndex(2)
        self.form_layout_adc_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.adc_Bits)
        self.form_layout_adc_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.adc_Bits_cb)
        # ADC Format
        self.adc_Format = QLabel(self.strings['StartFrame']['adc_Format'][0])
        self.adc_Format.setToolTip(self.strings['StartFrame']['adc_Format'][1])
        self.adc_Format_cb = QComboBox()
        self.adc_Format_cb.addItem(self.strings['StartFrame']['adc_Format'][2], 0)
        self.adc_Format_cb.addItem(self.strings['StartFrame']['adc_Format'][3], 1)
        self.adc_Format_cb.addItem(self.strings['StartFrame']['adc_Format'][4], 2)
        self.adc_Format_cb.addItem(self.strings['StartFrame']['adc_Format'][5], 3)
        self.adc_Format_cb.setCurrentIndex(2)
        self.form_layout_adc_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.adc_Format)
        self.form_layout_adc_conf.setWidget(1, QFormLayout.ItemRole.FieldRole, self.adc_Format_cb)
        # IQ swap
        self.iq_swap = QLabel(self.strings['StartFrame']['iqSwapSel'][0])
        self.iq_swap_cb = QComboBox()
        self.iq_swap_cb.addItem(self.strings['StartFrame']['iqSwapSel'][1], 0)
        self.iq_swap_cb.addItem(self.strings['StartFrame']['iqSwapSel'][2], 1)
        self.form_layout_adc_conf.setWidget(2, QFormLayout.ItemRole.LabelRole, self.iq_swap)
        self.form_layout_adc_conf.setWidget(2, QFormLayout.ItemRole.FieldRole, self.iq_swap_cb)
        self.ADC_out_config_gb.setLayout(self.form_layout_adc_conf)

        # Low Power configuration mode gb
        self.LP_config_gb = QGroupBox(self.strings['StartFrame']['GroupBoxes'][2])
        self.form_layout_lp_config = QFormLayout()
        self.main_layout.addWidget(self.LP_config_gb)
        # lp Adc Mode
        self.lp_Adc_Mode = QLabel(self.strings['StartFrame']['lp_Adc_Mode'][0])
        self.lp_Adc_Mode.setToolTip(self.strings['StartFrame']['lp_Adc_Mode'][1])
        self.lp_Adc_Mode_cb = QComboBox()
        self.lp_Adc_Mode_cb.addItem(self.strings['StartFrame']['lp_Adc_Mode'][2], 0)
        self.lp_Adc_Mode_cb.addItem(self.strings['StartFrame']['lp_Adc_Mode'][3], 1)
        self.lp_Adc_Mode_cb.model().item(1).setEnabled(False)
        self.form_layout_lp_config.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lp_Adc_Mode)
        self.form_layout_lp_config.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lp_Adc_Mode_cb)
        self.LP_config_gb.setLayout(self.form_layout_lp_config)

        # Data Path configuration parameters gb
        self.DP_config_gb = QGroupBox(self.strings['StartFrame']['GroupBoxes'][3])
        self.form_layout_dp_conf = QFormLayout()
        self.main_layout.addWidget(self.DP_config_gb)
        # intfSel
        self.data_Path = QLabel(self.strings['StartFrame']['data_Path'][0])
        self.data_Path.setToolTip(self.strings['StartFrame']['data_Path'][1])
        self.data_Path_cb = QComboBox()
        self.data_Path_cb.addItem(self.strings['StartFrame']['data_Path'][2], 0)
        self.data_Path_cb.addItem(self.strings['StartFrame']['data_Path'][3], 1)
        self.data_Path_cb.setCurrentIndex(1)
        self.data_Path_cb.model().item(0).setEnabled(False)
        self.form_layout_dp_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.data_Path)
        self.form_layout_dp_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.data_Path_cb)
        # Transfer Format Packet 0
        self.Pkt0 = QLabel(self.strings['StartFrame']['Pkt0'][0])
        self.Pkt0.setToolTip(self.strings['StartFrame']['Pkt0'][1])
        self.Pkt0_cb = QComboBox()
        self.Pkt0_cb.addItem(self.strings['StartFrame']['Pkt0'][2], 0)
        self.Pkt0_cb.addItem(self.strings['StartFrame']['Pkt0'][3], 1)
        self.Pkt0_cb.addItem(self.strings['StartFrame']['Pkt0'][4], 2)
        self.Pkt0_cb.addItem(self.strings['StartFrame']['Pkt0'][5], 3)
        self.Pkt0_cb.setCurrentIndex(1)
        self.form_layout_dp_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.Pkt0)
        self.form_layout_dp_conf.setWidget(1, QFormLayout.ItemRole.FieldRole, self.Pkt0_cb)
        # Transfer Format Packet 1
        self.Pkt1 = QLabel(self.strings['StartFrame']['Pkt1'][0])
        self.Pkt1.setToolTip(self.strings['StartFrame']['Pkt1'][1])
        self.Pkt1_cb = QComboBox()
        self.Pkt1_cb.addItem(self.strings['StartFrame']['Pkt1'][2], 0)
        self.Pkt1_cb.addItem(self.strings['StartFrame']['Pkt1'][3], 1)
        self.Pkt1_cb.addItem(self.strings['StartFrame']['Pkt1'][4], 2)
        self.form_layout_dp_conf.setWidget(2, QFormLayout.ItemRole.LabelRole, self.Pkt1)
        self.form_layout_dp_conf.setWidget(2, QFormLayout.ItemRole.FieldRole, self.Pkt1_cb)
        # CQ configuration
        self.cq_conf = QLabel(self.strings['StartFrame']['cq_conf'][0])
        self.cq_conf.setToolTip(self.strings['StartFrame']['cq_conf'][1])
        self.cq_conf_cb = QComboBox()
        self.cq_conf_cb.addItem(self.strings['StartFrame']['cq_conf'][2], 0)
        self.cq_conf_cb.addItem(self.strings['StartFrame']['cq_conf'][3], 1)
        self.cq_conf_cb.addItem(self.strings['StartFrame']['cq_conf'][4], 2)
        self.cq_conf_cb.setCurrentIndex(2)
        self.form_layout_dp_conf.setWidget(3, QFormLayout.ItemRole.LabelRole, self.cq_conf)
        self.form_layout_dp_conf.setWidget(3, QFormLayout.ItemRole.FieldRole, self.cq_conf_cb)
        # CQ0 Trans Size
        self.cq0 = QLabel(self.strings['StartFrame']['cq0'][0])
        self.cq0.setToolTip(self.strings['StartFrame']['cq0'][1])
        self.cq0_sb = QSpinBox()
        self.cq0_sb.setMaximum(128)
        self.cq0_sb.setValue(128)
        self.form_layout_dp_conf.setWidget(4, QFormLayout.ItemRole.LabelRole, self.cq0)
        self.form_layout_dp_conf.setWidget(4, QFormLayout.ItemRole.FieldRole, self.cq0_sb)
        # CQ1 Trans Size
        self.cq1 = QLabel(self.strings['StartFrame']['cq1'][0])
        self.cq1.setToolTip(self.strings['StartFrame']['cq1'][1])
        self.cq1_sb = QSpinBox()
        self.cq1_sb.setMaximum(128)
        self.cq1_sb.setValue(128)
        self.form_layout_dp_conf.setWidget(5, QFormLayout.ItemRole.LabelRole, self.cq1)
        self.form_layout_dp_conf.setWidget(5, QFormLayout.ItemRole.FieldRole, self.cq1_sb)
        # CQ2 Trans Size
        self.cq2 = QLabel(self.strings['StartFrame']['cq2'][0])
        self.cq2.setToolTip(self.strings['StartFrame']['cq2'][1])
        self.cq2_sb = QSpinBox()
        self.cq2_sb.setMaximum(128)
        self.cq2_sb.setValue(72)
        self.form_layout_dp_conf.setWidget(6, QFormLayout.ItemRole.LabelRole, self.cq2)
        self.form_layout_dp_conf.setWidget(6, QFormLayout.ItemRole.FieldRole, self.cq2_sb)
        self.DP_config_gb.setLayout(self.form_layout_dp_conf)

        # LVDS clock configuration parameters gb
        self.LVDS_config_gb = QGroupBox(self.strings['StartFrame']['GroupBoxes'][4])
        self.form_layout_lvds_conf = QFormLayout()
        self.main_layout.addWidget(self.LVDS_config_gb)
        # Lane Clock
        self.lane_CLK = QLabel(self.strings['StartFrame']['lane_CLK'][0])
        self.lane_CLK.setToolTip(self.strings['StartFrame']['lane_CLK'][1])
        self.lane_CLK_cb = QComboBox()
        self.lane_CLK_cb.addItem(self.strings['StartFrame']['lane_CLK'][2], 0)
        self.lane_CLK_cb.addItem(self.strings['StartFrame']['lane_CLK'][3], 1)
        self.lane_CLK_cb.setCurrentIndex(0)
        self.lane_CLK_cb.model().item(1).setEnabled(False)
        self.form_layout_lvds_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane_CLK)
        self.form_layout_lvds_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane_CLK_cb)
        # Data Rate
        self.data_Rate = QLabel(self.strings['StartFrame']['data_Rate'][0])
        self.data_Rate.setToolTip(self.strings['StartFrame']['data_Rate'][1])
        self.data_Rate_cb = QComboBox()
        self.data_Rate_cb.addItem(self.strings['StartFrame']['data_Rate'][2], [1, 10])
        self.data_Rate_cb.addItem(self.strings['StartFrame']['data_Rate'][3], [2, 6])
        self.data_Rate_cb.addItem(self.strings['StartFrame']['data_Rate'][4], [3, 2])
        self.data_Rate_cb.addItem(self.strings['StartFrame']['data_Rate'][5], [4, 11])
        self.data_Rate_cb.addItem(self.strings['StartFrame']['data_Rate'][6], [5, 7])
        self.data_Rate_cb.addItem(self.strings['StartFrame']['data_Rate'][7], [6, 7])
        self.data_Rate_cb.setCurrentIndex(1)
        self.data_Rate_cb.model().item(0).setEnabled(False)
        self.data_Rate_cb.model().item(2).setEnabled(False)
        self.data_Rate_cb.model().item(4).setEnabled(False)
        self.data_Rate_cb.model().item(5).setEnabled(False)
        self.form_layout_lvds_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.data_Rate)
        self.form_layout_lvds_conf.setWidget(1, QFormLayout.ItemRole.FieldRole, self.data_Rate_cb)
        self.LVDS_config_gb.setLayout(self.form_layout_lvds_conf)

        # LVDS Lane configuration parameters gb
        self.LVDS_lane_config_gb = QGroupBox(self.strings['StartFrame']['GroupBoxes'][5])
        self.form_layout_lvds_lane_conf = QFormLayout()
        self.main_layout.addWidget(self.LVDS_lane_config_gb)
        # Lane Clock
        self.lane_Format = QLabel(self.strings['StartFrame']['lane_Format'][0])
        self.lane_Format.setToolTip(self.strings['StartFrame']['lane_Format'][1])
        self.lane_Format_cb = QComboBox()
        self.lane_Format_cb.addItem(self.strings['StartFrame']['lane_Format'][2], 0)
        self.lane_Format_cb.addItem(self.strings['StartFrame']['lane_Format'][3], 1)
        self.form_layout_lvds_lane_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane_Format)
        self.form_layout_lvds_lane_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane_Format_cb)
        # Lane Config
        self.lane_conf = QLabel(self.strings['StartFrame']['lane_conf'][0])
        self.lane_conf.setToolTip(self.strings['StartFrame']['lane_conf'][1])
        self.lane_h_layout = QHBoxLayout()
        self.lane_h_layout.addWidget(self.lane_conf)
        # Lane 1
        self.lane1_form = QFormLayout()
        self.lane1 = QLabel(self.strings['StartFrame']['lane_conf'][2])
        self.lane1_cb = QCheckBox()
        self.lane1_cb.setChecked(True)
        self.lane1_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane1)
        self.lane1_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane1_cb)
        self.lane_h_layout.addLayout(self.lane1_form)
        # Lane 2
        self.lane2_form = QFormLayout()
        self.lane2 = QLabel(self.strings['StartFrame']['lane_conf'][3])
        self.lane2_cb = QCheckBox()
        self.lane2_cb.setChecked(True)
        self.lane2_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane2)
        self.lane2_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane2_cb)
        self.lane_h_layout.addLayout(self.lane2_form)
        # Lane 3
        self.lane3_form = QFormLayout()
        self.lane3 = QLabel(self.strings['StartFrame']['lane_conf'][4])
        self.lane3_cb = QCheckBox()
        self.lane3_cb.setChecked(True)
        self.lane3_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane3)
        self.lane3_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane3_cb)
        self.lane_h_layout.addLayout(self.lane3_form)
        # Lane 4
        self.lane4_form = QFormLayout()
        self.lane4 = QLabel(self.strings['StartFrame']['lane_conf'][5])
        self.lane4_cb = QCheckBox()
        self.lane4_cb.setChecked(True)
        self.lane4_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane4)
        self.lane4_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane4_cb)
        self.lane_h_layout.addLayout(self.lane4_form)
        self.form_layout_lvds_lane_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.lane_conf)
        self.form_layout_lvds_lane_conf.setLayout(1, QFormLayout.ItemRole.FieldRole, self.lane_h_layout)
        # Lane Param configuration
        self.lane_param_conf = QLabel(self.strings['StartFrame']['lane_param_conf'][0])
        self.lane_param_conf.setToolTip(self.strings['StartFrame']['lane_param_conf'][1])
        self.lane_param_h_layout = QHBoxLayout()
        self.lane_param_h_layout.addWidget(self.lane_param_conf)
        # MSB First
        self.msb_form = QFormLayout()
        self.msb_first = QLabel(self.strings['StartFrame']['lane_param_conf'][2])
        self.msb_first.setToolTip(self.strings['StartFrame']['lane_param_conf'][3])
        self.msb_first_cb = QCheckBox()
        self.msb_first_cb.setChecked(True)
        self.msb_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.msb_first)
        self.msb_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.msb_first_cb)
        self.lane_param_h_layout.addLayout(self.msb_form)
        # CRC
        self.crc_form = QFormLayout()
        self.crc = QLabel(self.strings['StartFrame']['lane_param_conf'][4])
        self.crc.setToolTip(self.strings['StartFrame']['lane_param_conf'][5])
        self.crc_cb = QCheckBox()
        self.crc_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.crc)
        self.crc_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.crc_cb)
        self.lane_param_h_layout.addLayout(self.crc_form)
        # Packet End Pulse
        self.packet_end_pulse_form = QFormLayout()
        self.packet_end_pulse = QLabel(self.strings['StartFrame']['lane_param_conf'][6])
        self.packet_end_pulse.setToolTip(self.strings['StartFrame']['lane_param_conf'][7])
        self.packet_end_pulse_cb = QCheckBox()
        self.packet_end_pulse_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.packet_end_pulse)
        self.packet_end_pulse_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.packet_end_pulse_cb)
        self.lane_param_h_layout.addLayout(self.packet_end_pulse_form)
        self.form_layout_lvds_lane_conf.setWidget(2, QFormLayout.ItemRole.LabelRole, self.lane_param_conf)
        self.form_layout_lvds_lane_conf.setLayout(2, QFormLayout.ItemRole.FieldRole, self.lane_param_h_layout)
        self.LVDS_lane_config_gb.setLayout(self.form_layout_lvds_lane_conf)

        # Navigation and firmware config layout
        self.end_layout = QHBoxLayout()
        self.main_layout.addLayout(self.end_layout)
        # Firmware label
        self.firmware_label = QLabel(self.strings['StartFrame']['firmware'][0])
        self.firmware_label.setToolTip(self.strings['StartFrame']['firmware'][1])
        self.firmware_label.setSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)
        # Firmware checkbox
        self.firmware_cb = QCheckBox()
        self.firmware_cb.setChecked(True)
        self.firmware_cb.setDisabled(True)
        self.firmware_cb.setSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        self.end_layout.addWidget(self.firmware_label)
        self.end_layout.addWidget(self.firmware_cb)

        # Navigation gp
        self.navigation_gp = QGroupBox(self.strings['StartFrame']['GroupBoxes'][6])
        self.navigation_gp.setSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        self.navigation_gp.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.end_layout.addWidget(self.navigation_gp)
        self.navigation_layout = QHBoxLayout()
        # Next button
        self.next_button = QPushButton(self.strings['StartFrame']['navigation'][0])
        self.navigation_layout.addWidget(self.next_button)
        self.navigation_gp.setLayout(self.navigation_layout)
        # Config button
        self.open_nw_config_button = QPushButton(self.strings['StartFrame']['navigation'][1])
        self.navigation_layout.addWidget(self.open_nw_config_button)
        # Exit button
        self.exit_button = QPushButton(self.strings['StartFrame']['navigation'][2])
        self.navigation_layout.addWidget(self.exit_button)
