from PyQt6.QtWidgets import QFrame, QPushButton, QVBoxLayout, QHBoxLayout, QLabel, QGroupBox, \
    QSpinBox, QFormLayout, QCheckBox, QGridLayout, QComboBox
from PyQt6.QtCore import QTranslator, QLocale
import yaml


class StartFrame(QFrame):

    def __init__(self):
        super(StartFrame, self).__init__()

        self.strings = {}
        with open('C:\\Users\\kayaton\\PycharmProjects\\mmWave_config_tool\\resources\\strings\\strings.yaml') as f:
            self.strings = yaml.safe_load(f)

        self.translator = QTranslator()

        # Main layout
        self.main_layout = QVBoxLayout()
        self.setLayout(self.main_layout)

        # Channel configuration parameters gb
        self.channel_config_gb = QGroupBox('Channel configuration parameters')
        self.grid_layout_ch_config = QGridLayout()
        self.main_layout.addWidget(self.channel_config_gb)
        self.channel_config_gb.setLayout(self.grid_layout_ch_config)
        # channelTx
        self.channel_Tx = QLabel('channel Tx')
        self.channel_Tx.setToolTip(self.strings['StartFrame']['channel_Tx'][0])
        self.grid_layout_ch_config.addWidget(self.channel_Tx, 0, 0)
        # Tx0
        self.form_layout_Tx0 = QFormLayout()
        self.Tx0 = QLabel('Tx0')
        self.Tx0_sb = QCheckBox()
        self.Tx0_sb.setChecked(True)
        self.form_layout_Tx0.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Tx0)
        self.form_layout_Tx0.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Tx0_sb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Tx0, 0, 1)
        # Tx1
        self.Tx1 = QLabel('Tx1')
        self.form_layout_Tx1 = QFormLayout()
        self.Tx1_sb = QCheckBox()
        self.Tx1_sb.setChecked(True)
        self.form_layout_Tx1.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Tx1)
        self.form_layout_Tx1.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Tx1_sb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Tx1, 0, 2)
        # Tx2
        self.Tx2 = QLabel('Tx2')
        self.form_layout_Tx2 = QFormLayout()
        self.Tx2_sb = QCheckBox()
        self.form_layout_Tx2.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Tx2)
        self.form_layout_Tx2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Tx2_sb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Tx2, 0, 3)
        # channelRx
        self.channel_Rx = QLabel('channel Rx')
        self.channel_Rx.setToolTip(self.strings['StartFrame']['channel_Rx'][0])
        self.grid_layout_ch_config.addWidget(self.channel_Rx, 1, 0)
        # Rx0
        self.form_layout_Rx0 = QFormLayout()
        self.Rx0 = QLabel('Rx0')
        self.Rx0.setToolTip(self.strings['StartFrame']['channel_Rx'][0])
        self.Rx0_sb = QCheckBox()
        self.Rx0_sb.setChecked(True)
        self.form_layout_Rx0.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx0)
        self.form_layout_Rx0.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx0_sb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx0, 1, 1)
        # Rx1
        self.Rx1 = QLabel('Rx1')
        self.form_layout_Rx1 = QFormLayout()
        self.Rx1_sb = QCheckBox()
        self.Rx1_sb.setChecked(True)
        self.form_layout_Rx1.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx1)
        self.form_layout_Rx1.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx1_sb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx1, 1, 2)
        # Rx2
        self.Rx2 = QLabel('Rx2')
        self.form_layout_Rx2 = QFormLayout()
        self.Rx2_sb = QCheckBox()
        self.Rx2_sb.setChecked(True)
        self.form_layout_Rx2.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx2)
        self.form_layout_Rx2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx2_sb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx2, 1, 3)
        # Rx3
        self.Rx3 = QLabel('Rx3')
        self.form_layout_Rx3 = QFormLayout()
        self.Rx3_sb = QCheckBox()
        self.Rx3_sb.setChecked(True)
        self.form_layout_Rx3.setWidget(0, QFormLayout.ItemRole.LabelRole, self.Rx3)
        self.form_layout_Rx3.setWidget(0, QFormLayout.ItemRole.FieldRole, self.Rx3_sb)
        self.grid_layout_ch_config.addLayout(self.form_layout_Rx3, 1, 4)
        # Cascading Mode
        self.cascading_Mode = QLabel('Cascading Mode')
        self.cascading_Mode.setToolTip(self.strings['StartFrame']['cascading_Mode'][0])
        self.grid_layout_ch_config.addWidget(self.cascading_Mode, 2, 0)
        self.cascading_Mode_cb = QComboBox()
        self.cascading_Mode_cb.addItem('Single Chip', 0)
        self.cascading_Mode_cb.addItem('Master', 1)
        self.cascading_Mode_cb.addItem('Slave', 2)
        self.grid_layout_ch_config.addWidget(self.cascading_Mode_cb, 2, 1)

        # ADC out configuration parameters gb
        self.ADC_out_config_gb = QGroupBox('ADC out configuration parameters')
        self.form_layout_adc_conf = QFormLayout()
        self.main_layout.addWidget(self.ADC_out_config_gb)
        # ADC Bits
        self.adc_Bits = QLabel('ADC Bits')
        self.adc_Bits.setToolTip(self.strings['StartFrame']['adc_Bits'][0])
        self.adc_Bits_cb = QComboBox()
        self.adc_Bits_cb.addItem('12', 0)
        self.adc_Bits_cb.addItem('14', 1)
        self.adc_Bits_cb.addItem('16', 2)
        self.adc_Bits_cb.setCurrentIndex(2)
        self.form_layout_adc_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.adc_Bits)
        self.form_layout_adc_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.adc_Bits_cb)
        # ADC Format
        self.adc_Format = QLabel('ADC Format')
        self.adc_Format.setToolTip(self.strings['StartFrame']['adc_Format'][0])
        self.adc_Format_cb = QComboBox()
        self.adc_Format_cb.addItem('Real', 0)
        self.adc_Format_cb.addItem('Complex1x', 1)
        self.adc_Format_cb.addItem('Complex2x', 2)
        self.adc_Format_cb.addItem('PseudoReal', 3)
        self.adc_Format_cb.setCurrentIndex(2)
        self.form_layout_adc_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.adc_Format)
        self.form_layout_adc_conf.setWidget(1, QFormLayout.ItemRole.FieldRole, self.adc_Format_cb)
        self.ADC_out_config_gb.setLayout(self.form_layout_adc_conf)

        # Low Power configuration mode gb
        self.LP_config_gb = QGroupBox('Low Power configuration mode')
        self.form_layout_lp_config = QFormLayout()
        self.main_layout.addWidget(self.LP_config_gb)
        # lp Adc Mode
        self.lp_Adc_Mode = QLabel('LP Mode')
        self.lp_Adc_Mode.setToolTip(self.strings['StartFrame']['lp_Adc_Mode'][0])
        self.lp_Adc_Mode_cb = QComboBox()
        self.lp_Adc_Mode_cb.addItem('Regular ADC', 0)
        self.lp_Adc_Mode_cb.addItem('Low Power ADC', 1)
        self.form_layout_lp_config.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lp_Adc_Mode)
        self.form_layout_lp_config.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lp_Adc_Mode_cb)
        self.LP_config_gb.setLayout(self.form_layout_lp_config)

        # Data Path configuration parameters gb
        self.DP_config_gb = QGroupBox('Data Path configuration parameters')
        self.form_layout_dp_conf = QFormLayout()
        self.main_layout.addWidget(self.DP_config_gb)
        # intfSel
        self.data_Path = QLabel('Data Path')
        self.data_Path.setToolTip(self.strings['StartFrame']['data_Path'][0])
        self.data_Path_cb = QComboBox()
        self.data_Path_cb.addItem('CSI2', 0)
        self.data_Path_cb.addItem('LVDS', 1)
        self.data_Path_cb.addItem('SPI', 2)
        self.data_Path_cb.setCurrentIndex(1)
        self.form_layout_dp_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.data_Path)
        self.form_layout_dp_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.data_Path_cb)
        # Transfer Format Packet 0
        self.Pkt0 = QLabel('Transfer Format Packet 0')
        self.Pkt0.setToolTip(self.strings['StartFrame']['Pkt0'][0])
        self.Pkt0_cb = QComboBox()
        self.Pkt0_cb.addItem('ADC_ONLY', 0)
        self.Pkt0_cb.addItem('CP_ADC', 1)
        self.Pkt0_cb.addItem('ADC_CP', 2)
        self.Pkt0_cb.addItem('CP_ADC_CQ', 3)
        self.form_layout_dp_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.Pkt0)
        self.form_layout_dp_conf.setWidget(1, QFormLayout.ItemRole.FieldRole, self.Pkt0_cb)
        # Transfer Format Packet 1
        self.Pkt1 = QLabel('Transfer Format Packet 1')
        self.Pkt1.setToolTip(self.strings['StartFrame']['Pkt1'][0])
        self.Pkt1_cb = QComboBox()
        self.Pkt1_cb.addItem('Suppress Packet', 0)
        self.Pkt1_cb.addItem('CP_CQ', 1)
        self.Pkt1_cb.addItem('CQ_CP', 2)
        self.form_layout_dp_conf.setWidget(2, QFormLayout.ItemRole.LabelRole, self.Pkt1)
        self.form_layout_dp_conf.setWidget(2, QFormLayout.ItemRole.FieldRole, self.Pkt1_cb)
        # CQ configuration
        self.cq_conf = QLabel('CQ Configuration')
        self.cq_conf.setToolTip(self.strings['StartFrame']['cq_conf'][0])
        self.cq_conf_cb = QComboBox()
        self.cq_conf_cb.addItem('12', 0)
        self.cq_conf_cb.addItem('14', 1)
        self.cq_conf_cb.addItem('16', 2)
        self.cq_conf_cb.setCurrentIndex(2)
        self.form_layout_dp_conf.setWidget(3, QFormLayout.ItemRole.LabelRole, self.cq_conf)
        self.form_layout_dp_conf.setWidget(3, QFormLayout.ItemRole.FieldRole, self.cq_conf_cb)
        # CQ0 Trans Size
        self.cq0 = QLabel('CQ0 Trans Size')
        self.cq0.setToolTip(self.strings['StartFrame']['cq0'][0])
        self.cq0_sb = QSpinBox()
        self.cq0_sb.setMaximum(128)
        self.cq0_sb.setValue(128)
        self.form_layout_dp_conf.setWidget(4, QFormLayout.ItemRole.LabelRole, self.cq0)
        self.form_layout_dp_conf.setWidget(4, QFormLayout.ItemRole.FieldRole, self.cq0_sb)
        # CQ1 Trans Size
        self.cq1 = QLabel('CQ1 Trans Size')
        self.cq1.setToolTip(self.strings['StartFrame']['cq1'][0])
        self.cq1_sb = QSpinBox()
        self.cq1_sb.setMaximum(128)
        self.cq1_sb.setValue(128)
        self.form_layout_dp_conf.setWidget(5, QFormLayout.ItemRole.LabelRole, self.cq1)
        self.form_layout_dp_conf.setWidget(5, QFormLayout.ItemRole.FieldRole, self.cq1_sb)
        # CQ2 Trans Size
        self.cq2 = QLabel('CQ2 Trans Size')
        self.cq2.setToolTip(self.strings['StartFrame']['cq2'][0])
        self.cq2_sb = QSpinBox()
        self.cq2_sb.setMaximum(128)
        self.cq2_sb.setValue(72)
        self.form_layout_dp_conf.setWidget(6, QFormLayout.ItemRole.LabelRole, self.cq2)
        self.form_layout_dp_conf.setWidget(6, QFormLayout.ItemRole.FieldRole, self.cq2_sb)
        self.DP_config_gb.setLayout(self.form_layout_dp_conf)

        # LVDS clock configuration parameters gb
        self.LVDS_config_gb = QGroupBox('LVDS clock configuration parameters')
        self.form_layout_lvds_conf = QFormLayout()
        self.main_layout.addWidget(self.LVDS_config_gb)
        # Lane Clock
        self.lane_CLK = QLabel('Lane Clock')
        self.lane_CLK.setToolTip(self.strings['StartFrame']['lane_CLK'][0])
        self.lane_CLK_cb = QComboBox()
        self.lane_CLK_cb.addItem('SDR Clock', 0)
        self.lane_CLK_cb.addItem('DDR Clock', 1)
        self.lane_CLK_cb.setCurrentIndex(1)
        self.form_layout_lvds_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane_CLK)
        self.form_layout_lvds_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane_CLK_cb)
        # Data Rate
        self.data_Rate = QLabel('Data Rate')
        self.data_Rate.setToolTip(self.strings['StartFrame']['data_Rate'][0])
        self.data_Rate_cb = QComboBox()
        self.data_Rate_cb.addItem('900 Mbps', 0)
        self.data_Rate_cb.addItem('600 Mbps', 1)
        self.data_Rate_cb.addItem('450 Mbps', 2)
        self.data_Rate_cb.addItem('400 Mbps', 3)
        self.data_Rate_cb.addItem('300 Mbps', 4)
        self.data_Rate_cb.addItem('225 Mbps', 5)
        self.data_Rate_cb.addItem('150 Mbps', 6)
        self.data_Rate_cb.setCurrentIndex(1)
        self.form_layout_lvds_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.data_Rate)
        self.form_layout_lvds_conf.setWidget(1, QFormLayout.ItemRole.FieldRole, self.data_Rate_cb)
        self.LVDS_config_gb.setLayout(self.form_layout_lvds_conf)

        # LVDS Lane configuration parameters gb
        self.LVDS_lane_config_gb = QGroupBox('LVDS Lane configuration parameters')
        self.form_layout_lvds_lane_conf = QFormLayout()
        self.main_layout.addWidget(self.LVDS_lane_config_gb)
        # Lane Clock
        self.lane_Format = QLabel('Lane Format')
        self.lane_Format.setToolTip(self.strings['StartFrame']['lane_Format'][0])
        self.lane_Format_cb = QComboBox()
        self.lane_Format_cb.addItem('Format 0', 0)
        self.lane_Format_cb.addItem('Format 1', 1)
        self.form_layout_lvds_lane_conf.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane_Format)
        self.form_layout_lvds_lane_conf.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane_Format_cb)
        # Lane Config
        self.lane_conf = QLabel('Lane Config')
        self.lane_conf.setToolTip(self.strings['StartFrame']['lane_conf'][0])
        self.lane_h_layout = QHBoxLayout()
        self.lane_h_layout.addWidget(self.lane_conf)
        # Lane 1
        self.lane1_form = QFormLayout()
        self.lane1 = QLabel('Lane 1')
        self.lane1_cb = QCheckBox()
        self.lane1_cb.setChecked(True)
        self.lane1_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane1)
        self.lane1_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane1_cb)
        self.lane_h_layout.addLayout(self.lane1_form)
        # Lane 2
        self.lane2_form = QFormLayout()
        self.lane2 = QLabel('Lane 2')
        self.lane2_cb = QCheckBox()
        self.lane2_cb.setChecked(True)
        self.lane2_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane2)
        self.lane2_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane2_cb)
        self.lane_h_layout.addLayout(self.lane2_form)
        # Lane 3
        self.lane3_form = QFormLayout()
        self.lane3 = QLabel('Lane 3')
        self.lane3_cb = QCheckBox()
        self.lane3_cb.setChecked(True)
        self.lane3_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane3)
        self.lane3_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane3_cb)
        self.lane_h_layout.addLayout(self.lane3_form)
        # Lane 4
        self.lane4_form = QFormLayout()
        self.lane4 = QLabel('Lane 4')
        self.lane4_cb = QCheckBox()
        self.lane4_cb.setChecked(True)
        self.lane4_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lane4)
        self.lane4_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.lane4_cb)
        self.lane_h_layout.addLayout(self.lane4_form)
        self.form_layout_lvds_lane_conf.setWidget(1, QFormLayout.ItemRole.LabelRole, self.lane_conf)
        self.form_layout_lvds_lane_conf.setLayout(1, QFormLayout.ItemRole.FieldRole, self.lane_h_layout)
        # Lane Param configuration
        self.lane_param_conf = QLabel('Lane Param Config')
        self.lane_param_conf.setToolTip(self.strings['StartFrame']['lane_param_conf'][0])
        self.lane_param_h_layout = QHBoxLayout()
        self.lane_param_h_layout.addWidget(self.lane_param_conf)
        # MSB First
        self.msb_form = QFormLayout()
        self.msb_first = QLabel('MSB First')
        self.msb_first_cb = QCheckBox()
        self.msb_first_cb.setChecked(True)
        self.msb_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.msb_first)
        self.msb_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.msb_first_cb)
        self.lane_param_h_layout.addLayout(self.msb_form)
        # CRC
        self.crc_form = QFormLayout()
        self.crc = QLabel('CRC')
        self.crc_cb = QCheckBox()
        self.crc_form.setWidget(0, QFormLayout.ItemRole.LabelRole, self.crc)
        self.crc_form.setWidget(0, QFormLayout.ItemRole.FieldRole, self.crc_cb)
        self.lane_param_h_layout.addLayout(self.crc_form)
        self.form_layout_lvds_lane_conf.setWidget(2, QFormLayout.ItemRole.LabelRole, self.lane_param_conf)
        self.form_layout_lvds_lane_conf.setLayout(2, QFormLayout.ItemRole.FieldRole, self.lane_param_h_layout)
        self.LVDS_lane_config_gb.setLayout(self.form_layout_lvds_lane_conf)

        # Navigation gp
        self.navigation_gp = QGroupBox('Navigation')
        self.main_layout.addWidget(self.navigation_gp)
        self.navigation_layout = QHBoxLayout()
        # Exit button
        self.exit_button = QPushButton('Exit')
        self.navigation_layout.addWidget(self.exit_button)
        # Config button
        self.open_nw_config = QPushButton('Network configuration')
        self.navigation_layout.addWidget(self.open_nw_config)
        # Next button
        self.next_button = QPushButton('Next')
        self.navigation_layout.addWidget(self.next_button)
        self.navigation_gp.setLayout(self.navigation_layout)
